# Generated by Django 4.1.9 on 2023-06-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
