# Generated by Django 4.1.9 on 2023-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='img',
            field=models.URLField(),
        ),
    ]
